import fs from "node:fs";
import path from "node:path";
import AxeBuilder from "@axe-core/playwright";
import { expect, test, type Page } from "@playwright/test";
import { addDays, todayIn } from "../../src/lib/dates";
import { makeXlsx } from "../fixtures/files";

// The plan (TASK-013): month grid, day view, week view, moving a post, posts without a slot, history, "Danes".
const MAIL_DIR = path.resolve("test-results/mail");
function latestLinkTo(email: string): string | undefined {
  if (!fs.existsSync(MAIL_DIR)) return undefined;
  for (const f of fs.readdirSync(MAIL_DIR).sort().reverse()) {
    const m = JSON.parse(fs.readFileSync(path.join(MAIL_DIR, f), "utf8"));
    if (m.to === email && m.subject.includes("Prijava")) return m.text.match(/https?:\/\/\S+/)![0];
  }
}
async function signIn(page: Page, email: string) {
  const before = latestLinkTo(email);
  await page.goto("/login");
  await page.getByLabel("E-pošta").fill(email);
  await page.getByRole("button", { name: "Pošlji povezavo" }).click();
  await expect.poll(() => latestLinkTo(email), { timeout: 10_000 }).not.toBe(before);
  await page.goto(latestLinkTo(email)!);
  await expect(page).toHaveURL(/\/app$/);
}
const serious = async (page: Page) =>
  (await new AxeBuilder({ page }).analyze()).violations.filter((v) => v.impact === "serious" || v.impact === "critical").map((v) => `${v.id}: ${v.nodes[0]?.target}`);

test("plan: calendar, day and week views, moving a post, no slot, history, today on the dashboard", async ({ page, browser }, info) => {
  test.skip(info.project.name !== "desktop", "one full flow is enough; the phone agenda is checked at the end");
  test.setTimeout(90_000);
  const stamp = Date.now();
  const owner = `koledar-${stamp}@example.test`;
  const today = todayIn();
  const tomorrow = addDays(today, 1);
  await signIn(page, "e2e-root@example.test");
  await page.goto("/admin/orgs/new");
  await page.getByLabel("Ime", { exact: true }).fill("Koledar E2E");
  await page.getByLabel("Kratko ime (slug)").fill(`koledar-${stamp}`);
  await page.getByLabel("E-pošta lastnika").fill(owner);
  await page.getByRole("button", { name: "Ustvari" }).click();
  await expect(page.getByRole("heading", { name: "Koledar E2E" })).toBeVisible();

  const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const p = await ctx.newPage();
  await signIn(p, owner);
  await p.goto("/app/brands/new");
  await p.getByLabel("Ime", { exact: true }).fill("Inženirji");
  await p.getByLabel("Kratko ime (slug)").fill("inzenirji");
  await p.getByRole("button", { name: "Ustvari" }).click();
  const tab = (name: string) => p.getByRole("navigation", { name: "Razdelki branda" }).getByRole("link", { name }).click();
  await tab("Kanali");
  await p.getByLabel("Platforma").selectOption("instagram");
  await p.getByLabel("Profil (@ime)").fill("@inzenirji");
  await p.getByRole("button", { name: "Dodaj kanal" }).click();
  await expect(p.getByTestId("channels")).toContainText("@inzenirji");
  // One post without a slot (generated by hand).
  await tab("Objave");
  await p.getByLabel("Kaj objavimo?").fill("Brez termina");
  await p.getByRole("button", { name: "Ustvari objavo" }).click();
  await expect(p).toHaveURL(/\/app\/posts\//);

  // A small plan: two posts today, one tomorrow, one already published three days ago.
  const plan = makeXlsx([{ name: "IG", rows: [
    ["Datum", "Ura", "Platforma", "Račun", "Tema", "Besedilo", "Status"],
    [today, "18:00", "Instagram", "@inzenirji", "Večer", "Zvečer objavimo to.", "pending"],
    [today, "09:00", "Instagram", "@inzenirji", "Jutro", "Zjutraj objavimo to.", "pending"],
    [tomorrow, "", "Instagram", "@inzenirji", "Jutri", "", "pending"],
    [addDays(today, -3), "12:00", "Instagram", "@inzenirji", "Lani", "To je že objavljeno.", "objavljeno"],
  ] }]);
  await p.goto("/app/import");
  await p.getByLabel("Izberi plan").setInputFiles({ name: "plan.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: Buffer.from(plan) });
  await expect(p).toHaveURL(/\/app\/import\/[^/]+$/);
  await p.getByRole("button", { name: "Uvozi 4 objav" }).click();
  await expect(p).toHaveURL(/\/app\/posts\?import=/);

  // Month grid: today's cell lists both posts in time order, tomorrow's the planned one.
  await p.getByRole("navigation", { name: "Glavna navigacija" }).getByRole("link", { name: "Plan", exact: true }).click();
  const cell = (d: string) => p.getByTestId("plan-grid").locator(`[data-day="${d}"]`);
  await expect(cell(today).getByRole("link")).toHaveText([String(Number(today.slice(8))), "09:00 IG · Zjutraj objavimo to.", "18:00 IG · Zvečer objavimo to."]);
  expect(await serious(p)).toEqual([]);
  await p.screenshot({ path: info.outputPath("plan-month.png"), fullPage: true });
  // Tomorrow may be in the next month's grid (end of month): open the month that contains it.
  await p.goto(`/app/plan?d=${tomorrow}`);
  await expect(cell(tomorrow)).toContainText("Jutri");
  await p.goto("/app/plan");

  // Day view from the day number; week view.
  await cell(today).getByRole("link").first().click();
  await expect(p.getByTestId("plan-day").getByRole("row")).toHaveCount(3);
  await expect(p.getByTestId("plan-day").getByRole("row").nth(1)).toContainText("09:00");
  expect(await serious(p)).toEqual([]);
  await p.getByRole("navigation", { name: "Pogled" }).getByRole("link", { name: "Teden" }).click();
  await expect(p.getByTestId("plan-grid")).toContainText("Zjutraj objavimo to.");

  // Move the evening post to tomorrow 07:30 from its page.
  await p.goto("/app/plan?view=day");
  await p.getByRole("link", { name: "Zvečer objavimo to." }).click();
  await p.getByLabel("Dan", { exact: true }).fill(tomorrow);
  await p.getByLabel("Ura", { exact: true }).fill("07:30");
  await p.getByRole("button", { name: "Shrani termin" }).click();
  await expect(p.getByTestId("plan")).toContainText("07:30");
  await p.goto("/app/plan");
  await expect(cell(today)).not.toContainText("Zvečer");
  await p.goto(`/app/plan?d=${tomorrow}`);
  await expect(cell(tomorrow).getByRole("link").nth(1)).toHaveText("07:30 IG · Zvečer objavimo to.");

  // No slot and history tabs.
  await p.getByRole("navigation", { name: "Pogledi plana" }).getByRole("link", { name: /Brez termina/ }).click();
  await expect(p.getByTestId("plan-unscheduled")).toContainText("Brez termina");
  await p.getByRole("navigation", { name: "Pogledi plana" }).getByRole("link", { name: /Zgodovina/ }).click();
  await expect(p.getByTestId("plan-history").getByRole("row")).toHaveCount(2);
  await expect(p.getByTestId("plan-history")).toContainText("To je že objavljeno.");

  // Dashboard: today.
  await p.goto("/app");
  await expect(p.getByTestId("today-posts").getByRole("row")).toHaveCount(2);
  await expect(p.getByTestId("today-posts")).toContainText("Zjutraj objavimo to.");

  // Phone: the grid becomes an agenda.
  await p.setViewportSize({ width: 390, height: 844 });
  await p.goto("/app/plan");
  await expect(p.getByTestId("plan-grid")).toBeHidden();
  await expect(p.getByTestId("plan-agenda")).toContainText("Zjutraj objavimo to.");
  expect(await serious(p)).toEqual([]);
  await ctx.close();
});
