// Tables are added per task. Every tenant table must have `org_id` (ADR-005).
export * from "./schema/auth";
export * from "./schema/org";
export * from "./schema/audit";
export * from "./schema/platform";
export * from "./schema/brands";
export * from "./schema/brand-files";
export * from "./schema/plans";
export * from "./schema/generation";
export * from "./schema/bulk";
export * from "./schema/oauth";
export * from "./schema/mcp";
export * from "./schema/media";
export * from "./schema/design";
export * from "./schema/ideas";
export * from "./schema/ads";
export * from "./schema/personas";
export * from "./schema/competitors";
export * from "./schema/reviews";
